[package]
name = "merlin"
version = "0.1.0"
authors = ["geremachek <mrender2005@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "2.33.3"
default-features = false

